name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build solution
        run: msbuild FuzeGamepad.sln /p:Configuration=Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            **/bin/Release/FuzeGamepad.exe

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "FuzeGamepad.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
